#!/usr/bin/env node

/**
 * Setup Script for AI-Only Mode
 * This script helps configure the HPT Report App for AI-only analysis
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

console.log('🚀 HPT Report App - AI-Only Mode Setup');
console.log('=====================================\n');

console.log('This script will configure your app for AI-only analysis mode.');
console.log('You will need a Perplexity API key to proceed.\n');

console.log('📋 What you need:');
console.log('1. Perplexity API account (https://www.perplexity.ai/)');
console.log('2. Valid API key with sufficient credits\n');

rl.question('Do you have a Perplexity API key? (y/n): ', (hasKey) => {
  if (hasKey.toLowerCase() !== 'y') {
    console.log('\n❌ You need a Perplexity API key to use AI-only mode.');
    console.log('\n📝 Steps to get your API key:');
    console.log('1. Visit https://www.perplexity.ai/');
    console.log('2. Sign up for an account');
    console.log('3. Navigate to API settings');
    console.log('4. Generate a new API key');
    console.log('5. Run this script again with your API key\n');
    rl.close();
    return;
  }

  rl.question('Enter your Perplexity API key: ', (apiKey) => {
    if (!apiKey || apiKey.trim().length === 0) {
      console.log('\n❌ Invalid API key. Please try again.');
      rl.close();
      return;
    }

    // Create .env.local file
    const envContent = `# HPT Report App - AI Configuration
# Generated by setup-ai-only.js on ${new Date().toISOString()}

# Perplexity API Configuration
PERPLEXITY_API_KEY=${apiKey.trim()}

# AI-Only Mode Configuration
ENABLE_AI_INSIGHTS=true
AI_FALLBACK_ENABLED=false

# This configuration ensures:
# ✅ All analysis uses AI for maximum insight quality
# ✅ No fallback to rule-based analysis
# ✅ Consistent AI-powered reports for all employees
# ✅ Advanced features like behavioral recommendations and risk analysis
`;

    const envPath = path.join(process.cwd(), '.env.local');
    
    try {
      fs.writeFileSync(envPath, envContent);
      
      console.log('\n✅ Configuration complete!');
      console.log('\n📁 Created: .env.local');
      console.log('\n🎯 AI-Only Mode Enabled:');
      console.log('   • ENABLE_AI_INSIGHTS=true');
      console.log('   • AI_FALLBACK_ENABLED=false');
      console.log('\n🚀 Next Steps:');
      console.log('1. Start your development server: npm run dev');
      console.log('2. Upload an Excel file to test AI analysis');
      console.log('3. All reports will now use AI-powered insights');
      console.log('\n💡 Benefits of AI-Only Mode:');
      console.log('   • Superior analysis quality');
      console.log('   • Personalized insights for each employee');
      console.log('   • Predictive performance analysis');
      console.log('   • Advanced behavioral recommendations');
      console.log('   • Risk factor identification');
      console.log('   • Team-level strategic insights');
      
      console.log('\n📖 For more information, see AI_SETUP.md');
      console.log('\n🔒 Security Note: Your API key is stored locally and never shared.');
      
    } catch (error) {
      console.log('\n❌ Error creating configuration file:', error.message);
      console.log('\nPlease create .env.local manually with the following content:');
      console.log('\n' + envContent);
    }
    
    rl.close();
  });
}); 